version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      TZ: America/Cancun
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  cripto:
    build: 
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    environment:
      - TZ=America/Cancun
    restart: always
    volumes:
      - ./src:/app
    depends_on:
      - db
# Names our volume
volumes:
  my-db: